- hosts: localhost
  tasks:
  - name: Install Nginx
    yum:
      name: nginx
      state: latest

  - name: Configure Nginx
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0644
      notify: restart nginx

  - name: Install PHP (assuming a PHP application)
    yum:
      name: php php-fpm

  - name: Configure PHP-FPM
    template:
      src: www.conf.j2
      dest: /etc/php-fpm.d/www.conf
      notify: restart php-fpm

  - name: Copy application files
    copy:
      src: /path/to/your/app/files
      dest: /var/www/html
      owner: nginx
      group: nginx
      mode: 0755

  - name: Create database (if required)
    mysql_db:
      name: my_app_db
      state: present

  - name: Grant database privileges (if required)
    mysql_user:
      name: my_app_user
      password: my_app_password
      priv: 'my_app_db.*:ALL'
      state: present

  - name: Configure logging
    template:
      src: nginx-logrotate.conf.j2
      dest: /etc/logrotate.d/nginx

  - name: Harden security
    blockinfile:
      path: /etc/sysctl.conf
      block: |
        net.ipv4.tcp_syncookies = 1
        net.ipv4.conf.all.accept_source_route = 0
        net.ipv4.conf.all.accept_redirects = 0
        net.ipv4.conf.all.secure_redirects = 0
        net.ipv4.conf.all.log_martians = 1

  - name: Disable SELinux (optional)
    selinux:
      state: disabled

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart php-fpm
      service:
        name: php-fpm
        state: restarted
